module.exports = {
  development: {
    appUrl: `http://localhost:${process.env.PORT}`,
    awabahVfdAccountNumber: process.env.AWABAH_VFD_DEV_POOL_ACCOUNT_NUMBER,
    cloudinaryCloudName: process.env.AWABAH_CLOUDINARY_CLOUD_NAME,
    cloudinaryApiKey: process.env.AWABAH_CLOUDINARY_API_KEY,
    cloudinaryApiSecret: process.env.AWABAH_CLOUDINARY_API_SECRET,
    database: process.env.AWABAH_DATABASE_DEV_URL,
    emailUsername: process.env.AWABAH_TEST_EMAIL_USERNAME,
    fcmbBaseUrl: process.env.AWABAH_DEV_FCMB_BASE_URL,
    leadwayAppKey: process.env.AWABAH_LEADWAY_DEV_APP_KEY,
    leadwayEmployerId: process.env.AWABAH_LEADWAY_DEV_EMPLOYER_ID,
    leadwayLppfaUsername: process.env.AWABAH_LEADWAY_DEV_LPPFA_USERNAME,
    leadwayNigeriaAbroad: process.env.AWABAH_LEADWAY_DEV_E_NIGERIA_ABROAD,
    leadwayRegistrationType: process.env.AWABAH_LEADWAY_DEV_REGISTRATION_TYPE,
    leadwayResidenceStatus: process.env.AWABAH_LEADWAY_DEV_RESIDENCE_STATUS,
    leadwaySectorId: process.env.AWABAH_LEADWAY_DEV_SECTOR_ID,
    myEmail: process.env.AWABAH_TEST_EMAIL_USERNAME,
    paystackSecretKey: process.env.AWABAH_PAYSTACK_DEV_SECRET_KEY,
    twilioAccountSid: process.env.AWABAH_TWILIO_DEV_TEST_ACCOUNT_SID,
    twilioAuthToken: process.env.AWABAH_TWILIO_DEV_TEST_AUTH_TOKEN,
    twilioFromNumber: process.env.AWABAH_TWILIO_DEV_TEST_FROM_NUMBER,
    verifyMeSecretKey: process.env.AWABAH_VERIFY_ME_DEV_SECRET_KEY,
    vfdWalletCredentials: process.env.AWABAH_VFD_DEV_WALLET_CREDENTIALS,
    vfdBaseUrl: process.env.AWABAH_VFD_DEV_BASE_URL,
    vfdToken: process.env.AWABAH_VFD_DEV_TOKEN,
    vfdTransferSource: process.env.AWABAH_VFD_TRANSFER_SOURCE,
  },
};
